name: Run Postman Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Tests
      run: newman run collections/Restful-booker.postman_collection.json -e environments/Restful-booker.postman_environment.json
